import 'package:flutter/material.dart';

// Colors
const kBackgroundColor = Color(0xFFFEFEFE);
const kTitleTextColor = Color(0xFF303030);
const kBodyTextColor = Color(0xFF4B4B4B);
const kTextLightColor = Color(0xFF959595);
const kInfectedColor = Color(0xFFFF8748);
const kDeathColor = Color(0xFFFF4848);
const kRecovercolor = Color(0xFF36C12C);
const kPrimaryColor = Color(0xFF3382CC);
final kShadowColor = Color(0xFFB7B7B7).withOpacity(.16);
final kActiveShadowColor = Color(0xFF4056C6).withOpacity(.15);

// Text Style
const kHeadingTextStyle = TextStyle(
  fontSize: 22,
  fontWeight: FontWeight.w600,
);

const kSubTextStyle = TextStyle(fontSize: 16, color: kTextLightColor);

const kTitleTextstyle = TextStyle(
  fontSize: 18,
  color: kTitleTextColor,
  fontWeight: FontWeight.bold,
);

//Url
const coronaBaseURL = "https://coronavirus-tracker-api.herokuapp.com/v2/";
const coronaLocationsURL = "locations";
 const Map<String,String > countriesCODE= {
"Ascension Island":'ac',
"Andorra":'ad',
"United Arab Emirates":'ae',
"Afghanistan":'af',
"Antigua And Barbuda":'ag',
"Anguilla":'ai',
"Albania":'al',
"Armenia":'am',
"Netherlands Antilles":'an',
"Angola":'ao',
"Antarctica":'aq',
"Argentina":'ar',
"American Samoa":'as',
"Austria":'at',
"Australia":'au',
"Aruba":'aw',
"Åland":'ax',
"Azerbaijan":'az',
"Bosnia And Herzegovina":'ba',
"Barbados":'bb',
"Belgium":'be',
"Bangladesh":'bd',
"Burkina Faso":'bf',
"Bulgaria":'bg',
"Bahrain":'bh',
"Burundi":'bi',
"Benin":'bj',
"Bermuda":'bm',
"Brunei Darussalam":'bn',
"Bolivia":'bo',
"Brazil":'br',
"Bahamas":'bs',
"Bhutan":'bt',
"Bouvet Island":'bv',
"Botswana":'bw',
"Belarus":'by',
"Belize":'bz',
"Canada":'ca',
"Cocos (Keeling) Islands":'cc',
"Congo (Democratic Republic)":'cd',
"Central African Republic":'cf',
"Congo (Republic)":'cg',
"Switzerland":'ch',
"Cote D’Ivoire":'ci',
"Cook Islands":'ck',
"Chile":'cl',
"Cameroon":'cm',
"People’s Republic of China":'cn',
"Colombia":'co',
"Costa Rica":'cr',
"Cuba":'cu',
"Cape Verde":'cv',
"Christmas Island":'cx',
"Cyprus":'cy',
"Czech Republic":'cz',
"Germany":'de',
"Djibouti":'dj',
"Denmark":'dk',
"Dominica":'dm',
"Dominican Republic":'do',
"Algeria":'dz',
"Ecuador":'ec',
"Estonia":'ee',
"Egypt":'eg',
"Eritrea":'er',
"Spain":'es',
"Ethiopia":'et',
"European Union":'eU',
"Finland":'fi',
"Fiji":'fj',
"Falkland Islands (Malvinas)":'fk',
"Micronesia, Federated States Of":'fm',
'Faroe Islands':'fo',
"France":'fr',
"Gabon":'ga',
'United Kingdom (no new registrations, see also UK)':'gb',
'Grenada':'gd',
'Georgia':'ge',
'French Guiana':'gf',
'Guernsey':'gg',
'Ghana':'gh',
'Gibraltar':'gi',
'Greenland':'gl',
'Gambia':'gm',
'Guinea':'gn',
'Guadeloupe':'gp',
'Equatorial Guinea':'gq',
'Greece':'gr',
'South Georgia And The South Sandwich Islands':'gs',
'Guatemala':'gt',
'Guam':'gu',
'Guinea-Bissau':'gw',
'Guyana':'gy',
'Hong Kong':'hk',
'Heard And Mc Donald Islands':'hm',
'Honduras':'hn',
'Croatia (local name: Hrvatska)':'hr',
'Haiti':'ht',
'Hungary':'hu',
'Indonesia':'id',
'Ireland':'ie',
'Israel':'il',
'Isle of Man':'im',
'India':'in',
'British Indian Ocean Territory':'io',
'Iraq':'iq',
'Iran (Islamic Republic Of)':'ir',
'Iceland':'is',
'Italy':'it',
'Jersey':'je',
'Jamaica':'jm',
'Jordan':'jo',
'Japan':'jp',
'Kenya':'ke',
'Kyrgyzstan':'kg',
'Cambodia':'kh',
'Kiribati':'ki',
'Comoros':'km',
'Saint Kitts And Nevis':'kn',
'Korea, Republic Of':'kr',
'Kuwait':'kw',
'Cayman Islands':'ky',
'Kazakhstan':'kz',
'Lao People’s Democratic Republic':'la',
'Lebanon':'lb',
'Saint Lucia':'lc',
'Liechtenstein':'li',
'Sri Lanka':'lk',
'Liberia':'lr',
'Lesotho':'ls',
'Lithuania':'lt',
'Luxembourg':'lu',
'Latvia':'lv',
'Libyan Arab Jamahiriya':'ly',
'Morocco':'ma',
'Monaco':'mc',
'Moldova, Republic Of':'md',
'Montenegro':'me',
'Madagascar':'mg',
'Marshall Islands':'mh',
'Macedonia, The Former Yugoslav Republic Of':'mk',
'Mali':'ml',
'Myanmar':'mm',
'Mongolia':'mn',
'Macau':'mo',
'Northern Mariana Islands':'mp',
'Martinique':'mq',
'Mauritania':'mr',
'Montserrat':'ms',
'Malta':'mt',
'Mauritius':'mu',
'Maldives':'mv',
'Malawi':'mw',
'Mexico':'mx',
'Malaysia':'my',
'Mozambique':'mz',
'Namibia':'na',
'New Caledonia':'nc',
'Niger':'ne',
'Norfolk Island':'nf',
'Nigeria':'ng',
'Nicaragua':'ni',
'Netherlands':'nl',
'Norway':'no',
'Nepal':'np',
'Nauru':'nr',
'Niue':'nu',
'New Zealand':'nz',
'Oman':'om',
'Panama':'pa',
'Peru':'pe',
'French Polynesia':'pf',
'Papua New Guinea':'pg',
'Philippines, Republic of the':'ph',
'Pakistan':'pk',
'Poland':'pl',
'St. Pierre And Miquelon':'pm',
'Pitcairn':'pn',
'Puerto Rico':'pr',
'Palestine':'ps',
'Portugal':'pt',
'Palau':'pw',
'Paraguay':'py',
'Qatar':'qa',
'Reunion':'re',
'Romania':'ro',
'Serbia':'rs',
'Russian Federation':'ru',
'Rwanda':'rw',
'Saudi Arabia':'sa',
'Scotland':'uk',
'Solomon Islands':'sb',
'Seychelles':'sc',
'Sudan':'sd',
'Sweden':'se',
'Singapore':'sg',
'St. Helena':'sh',
'Slovenia':'si',
'Svalbard And Jan Mayen Islands':'sj',
'Slovakia (Slovak Republic)':'sk',
'Sierra Leone':'sl',
'San Marino':'sm',
'Senegal':'sn',
'Somalia':'so',
'Suriname':'sr',
'Sao Tome And Principe':'st',
'Soviet Union':'su',
'El Salvador':'sv',
'Syrian Arab Republic':'sy',
'Swaziland':'sz',
'Turks And Caicos Islands':'tc',
'Chad':'td',
'French Southern Territories':'tf',
'Togo':'tg',
'Thailand':'th',
'Tajikistan':'tj',
'Tokelau':'tk',
'East Timor (new code)':'ti',
'Turkmenistan':'tm',
'Tunisia':'tn',
'Tonga':'to',
'East Timor (old code)':'tp',
'Turkey':'tr',
'Trinidad And Tobago':'tt',
'Tuvalu':'tv',
'Taiwan':'tw',
'Tanzania, United Republic Of':'tz',
'Ukraine':'ua',
'Uganda':'ug',
'United Kingdom':'uk',
'United States Minor Outlying Islands':'um',
'United States':'us',
'Uruguay':'uy',
'Uzbekistan':'uz',
'Vatican City State (Holy See)':'va',
'Saint Vincent And The Grenadines':'vc',
'Venezuela':'ve',
'Virgin Islands (British)':'vg',
'Virgin Islands (U.S.)':'vi',
'Viet Nam':'vn',
'Vanuatu':'vu',
'Wallis And Futuna Islands':'wf',
'Samoa':'ws',
'Yemen':'ye',
'Mayotte':'yt',
'South Africa':'za',
'Zambia':'zm',
'Zimbabwe':'zw',

};

